### PR TITLE
Use discovery document for api locations

### PR DESCRIPTION
**Pull request by ChrisPenner**
## The problem

The most concrete problem was that we had a mismatch between the bare Sync API type, and where it was hosted on Enlil. Servant didn't know to look at `/sync`. This addresses that issue by allowing the server to tell UCM where it hosts the Sync API, while this solution is probably a bit over-engineered for what we need right now, it also provides some bonus benefits:

* We want to be able to easily specify share server locations, both in config and user input, e.g. `pull share(https://my-cool-codeserver:1234/unison).base`
* BUT there are several APIs we need to access, and don't want to impose arbitrary limits on how APIs are actually structured. E.g. maybe your Authorization server is at `/oauth/authorization`, but your sync implementation is at `/blarg/foobar`, how do we know where to find these when they're potentially spread out?
* We want to keep the syntax clean and intuitive
* Its very helpful if we can determine which codeserver is which by just looking at the origin/host, since that's the safest way to determine which credentials to use for which codeserver.

## Solution

* The user specifies the single URI, UCM fetches `<uri>/.codeserver` to get a document which describes the rest of the API. This document can then be cached for the length of the UCM session.

Benefits:
* Most servers (e.g. share) will just host this at the root, so the 'simplest syntax' works, e.g. `share(https://share.unison-lang.org)`;
* UCM provides its expected codeserver version, so we can serve different API descriptions to different client versions which should make maintaining older versions of server endpoints much easier.
* We can move and rename our API structure whenever we want, UCM's will re-detect the new endpoints the next time they interact with the server.
* We may wish to add other information here which shouldn't be hard-coded into the client.
  * E.g. We could provide the amount of parallelism the client should use; Or could even assign the UCM instance a "preferred instance" so it has better cache locality.
* Codeservers have full flexibility in how they structure their APIs, as long as all their endpoints are on the same host.

## Implementation

* Makes a new distinction between a `CodeserverLocation` and a `Codeserver`; the former is a URL from which we can find the codeserver document, the latter contains all the information from a resolved codeserver (including API locations, etc.). 
* The CodeserverLocation is parsed from CLI commands, then HandleInput resolves it into API locations before handing it off to combinators.
* Pass the `syncAPIRoot` from the Codeserver description directly to the sync servant client rather than trying to guess where it belongs.

Example codeserver discovery doc

```json
{
"sync_api_root": "http://localhost:5424/sync",
"codeserver_version": 1,
"open_id_connect_discovery_location": "http://localhost:5424/.well-known/openid-configuration"
}
```

- - -
This change is [Reviewable](https://reviewable.io/reviews/unisonweb/unison/3103)

### CODE REVIEW

**Comment by ChrisPenner** [comment]
Failing CI because `arya/ooo-sync` is broken 😢

**Comment by aryairani** [comment]
> Failing CI because `arya/ooo-sync` is broken 😢

I'm not sure what we're seeing here; `arya/ooo-sync` doesn't seem to have been broken recently: https://github.com/unisonweb/unison/pull/3039

**Comment by ChrisPenner** [comment]
@aryairani  huh; I'll try re-merging, but these errors aren't from anything I touched in this PR 🤔 

```
 /home/runner/work/unison/unison/unison/unison-cli/src/Unison/Share/Sync.hs:363:1: error: [-Wunused-top-binds, -Werror=unused-top-binds]
        Defined but not used: ‘pull'’
        |
    363 | pull' httpClient unisonShareUrl conn repoPath@(Share.pathRepoName -> repoName) downloadCountCallback = do
        | ^^^^^
    /home/runner/work/unison/unison/unison/unison-cli/src/Unison/Share/Sync.hs:479:1: error: [-Wunused-top-binds, -Werror=unused-top-binds]
        Defined but not used: ‘downloadMissingDependenciesOf’
        |
    479 | downloadMissingDependenciesOf httpClient unisonShareUrl conn repoName hashes0 initialCount downloadCountCallback = do
        | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    /home/runner/work/unison/unison/unison/unison-cli/src/Unison/Share/Sync.hs:577:1: error: [-Wunused-top-binds, -Werror=unused-top-binds]
        Defined but not used: ‘elaborateHashes'’
        |
    577 | elaborateHashes' hashes = do
        | ^^^^^^^^^^^^^^^^
```

**Comment by aryairani** [comment]
> @aryairani huh; I'll try re-merging, but these errors aren't from anything I touched in this PR 🤔

Possibly a bad merge at some point?

**Comment by aryairani** [comment]
> * BUT there are several APIs we need to access, and don't want to impose arbitrary limits on how APIs are actually structured. E.g. maybe your Authorization server is at `/oauth/authorization`, but your sync implementation is at `/blarg/foobar`, how do we know where to find these when they're potentially spread out?

Why do we care about this, or how was this issue coming up?

**Comment by aryairani** [comment]
> * Its very helpful if we can determine which codeserver is which by just looking at the origin/host, since that's the safest way to determine which credentials to use for which codeserver.

I get this bullet now, but this was the case before this PR, right?

**Comment by ChrisPenner** [comment]
> I get this bullet now, but this was the case before this PR, right?

We were doing this, but in order to refresh tokens I needed to save the discovery document URL along with the credentials. Not a huge deal either way TBH

File: parser-typechecker/src/Unison/Codebase/Editor/RemoteRepo.hs [hunk 1]
```diff
@@ -99,10 +124,10 @@ maybePrintPath path =
     then mempty
     else "." <> Path.toText path
 
-data ReadRemoteNamespace
+data ReadRemoteNamespace server
```
Comment (aryairani) [inline parser-typechecker/src/Unison/Codebase/Editor/RemoteRepo.hs:127]: This change (and corresponding on `ReadShareRemoteNamespace`, `WriteRemotePath`, `WriteShareRemotePath`) seems a little weird to me.

I guess it is a type that evolves during discovery from one parameter to another? But maybe it should be separate from this data structure that has to do with Git too.

Comment (ChrisPenner) [reply parser-typechecker/src/Unison/Codebase/Editor/RemoteRepo.hs:127]: It's parameterized by the information we have about the server at a given point in time.

We parse it as a `CodeserverLocation` which is just a URI for the server, then we 'resolve' it to a full `Codeserver`, so after that we now have information about the locations of the sync api and auth apis, codeserver version, etc.

Semantically I think it makes sense for these types to be parameterized over the codeserver info, It could be different types, but since it's sometimes nested deeply it would require spinning up copies of all of those types too. It's pretty convenient to just be able to traverse with `resolve` instead, and avoids a bunch of boilerplate.

Comment (aryairani) [reply parser-typechecker/src/Unison/Codebase/Editor/RemoteRepo.hs:127]: It makes sense to parameterize Share-related stuff over Share-related stuff, but it seems fishy to me to parameterize Git or other kinds of repos over Share-related stuff or vice versa. An arbitrary, privileged `Traversable` instance that's the share stuff. Second opinions? @mitchellwrosen @tstat

File: parser-typechecker/src/Unison/Share/Types.hs [hunk 2]
```diff
@@ -123,24 +127,72 @@ newtype CodeserverId = CodeserverId {codeserverId :: Text}
...
+        "open_id_connect_discovery_location" .= uriJSON openIDConnectDiscoveryLocation,
+        "codeserver_version" .= codeserverVersion
+      ]
+    where
+      uriJSON :: URI -> Value
+      uriJSON = toJSON . show
+
+-- | Whether this is a codeserver specified by the user or the default Share codeserver.
+-- This information is used in formatting codeserver paths.
+data CodeserverProvidence = DefaultCodeserver | CustomCodeserver
```
Comment (aryairani) [inline parser-typechecker/src/Unison/Share/Types.hs]: This should probably be `Provenance` also

File: parser-typechecker/src/Unison/Codebase/Editor/RemoteRepo.hs (hunk 1 above)
Comment (ChrisPenner) [reply parser-typechecker/src/Unison/Codebase/Editor/RemoteRepo.hs:127]: I don't personally find it confusing to have parameters on types like this, I usually just jump-to-definition and see what it's used for, or ignore it entirely if I don't need to interact with it; I tend to find the proliferation of multiple 'identical except for this one deeply nested change' types more confusing, but maybe that's just me.

In this case I'm especially not worried since Share is the new "standard" and git will be slowly phased out over time.

**Comment by ChrisPenner** [comment]
Closing due to inactivity
