### PR TITLE
Revert "update to ghc 8.10.3"

### PR DESCRIPTION
**Pull request by aryairani**
Reverts unisonweb/unison#1777; it no longer builds?

### CODE REVIEW

**Comment by aryairani** [comment]
I had a build error I didn't understand, locally:
```
unison-parser-typechecker> /Users/arya/unison/parser-typechecker/tests/Unison/Test/ANF.hs:150:45: error:
unison-parser-typechecker>     Not in scope: type constructor or class ‘ANormalBF’
unison-parser-typechecker>     Perhaps you meant one of these:
unison-parser-typechecker>       ‘ANormalF’ (imported from Unison.Runtime.ANF),
unison-parser-typechecker>       ‘ANormal’ (imported from Unison.Runtime.ANF)
unison-parser-typechecker>     |         
unison-parser-typechecker> 150 | denormalizeBranch :: (Num a, Var v) => Term ANormalBF v -> (a, ABT.Term (Term.F v () ()) v ())
unison-parser-typechecker>     |                                             ^^^^^^^^^
unison-parser-typechecker>   
```
and I also saw a CI failure on `trunk` after merging #1777, and I assumed they were related, but now I don't think they are; yet I still don't understand them.
